---
version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:3000'
      - '443:3000'
    links:
      - umami
    restart: always
    environment:
      DOMAINS: 'www.trustless-services.duckdns.org -> http://umami'
      STAGE: 'production'
      # FORCE_RENEW: 'true'
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
volumes:
  umami-db-data:
